version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - type: bind
        source: ./.db
        target: /var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-P",
          "3306"
        ]
      interval: 30s
      timeout: 3s
      retries: 10

  wordpress1:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    restart: always
    environment:
      WP_POST_REVISIONS: 9
      DISALLOW_FILE_EDIT: true
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp1_
    volumes:
      - type: bind
        source: ./public
        target: /var/www/html
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      retries: 10

  wordpress2:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:latest
    restart: always
    environment:
      WP_POST_REVISIONS: 9
      DISALLOW_FILE_EDIT: true
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspassword
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp2_
    volumes:
      - type: volume
        source: wp2
        target: /var/www/html
    healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 30s
      retries: 10

  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - type: bind
        source: proxy.conf
        target: /etc/nginx/conf.d/proxy.conf

