version: "3.8"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpressuser
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - type: bind
        source: ./.db
        target: /var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
  wordpress1:
    image: wordpress:latest
  wordpress2:
    image: wordpress:latest

